image:
  registry: docker.io
  repository: bitnami/postgresql
  tag:  11.16.0

auth:
  username: kong
  password: kong
  database: api-gw

primary:
  standby:
    enabled: false

  service:
    type: NodePort
    nodePorts:
      postgresql: 30432

  persistence:
    enabled: true
    size: 4Gi
