apiVersion: v1
kind: Service
metadata:
  name: kong-svc
spec:
  selector:
    app: kong
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http
    nodePort: 30080
    name: http
  - protocol: TCP
    port: 8001
    targetPort: admin-http
    nodePort: 30081
    name: admin-http
  - protocol: TCP
    port: 8443
    targetPort: https
    nodePort: 30443
    name: https
  - protocol: TCP
    port: 8444
    targetPort: admin-https
    nodePort: 30444
    name: admin-https